[package]
name = "dominantcolors"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "dominantcolors"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
image = "0.24.7"
kmeans_colors = "0.6.0"
palette = "0.7.3"
rustler = "0.30.0"
